# Generated by Django 2.1 on 2018-11-14 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todoitem_sample'),
    ]

    operations = [
        migrations.CreateModel(
            name='todosample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='sample',
        ),
    ]
