# Generated by Django 2.1 on 2018-11-14 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20181115_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='fn',
            field=models.TextField(null=True),
        ),
    ]
