# Generated by Django 2.1 on 2018-11-15 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_todoitem_fn'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('phoneNumber', models.IntegerField()),
                ('address', models.TextField(null=True)),
                ('pinCode', models.IntegerField()),
            ],
        ),
    ]
